baseURL: 'https://cryingbear.net/'
languageCode: en-us
title: Crying Bear Studio
sectionPagesMenu: main

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod

markup:
    goldmark:
        renderer:
            unsafe: true

params:
  mainSections:
    - articles
