baseURL: 'http://www.cryingbear.net/'
languageCode: en-us
title: Crying Bear Studio
sectionPagesMenu: main
# buildExpired: true

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod

markup:
    goldmark:
        renderer:
            unsafe: true

params:
  mainSections:
    - articles
